# Natural convection by 'thermal' compressibility model
#
run:
	$(ELMER_HOME)/bin/ElmerGrid 1 2 ThermalCompress
	$(ELMER_HOME)/bin/Solver

clean:
	/bin/rm test.log temp.log mon.out
	/bin/rm -r ThermalCompress
