#!/bin/sh
if which ng 1> /dev/null 2> /dev/null
then
  ng -batchmode -meshfiletype="Elmer Format" -geofile=$1 -meshfile=$2 -meshsizefile=$3
else
  echo "ERROR: ng not found, unable to generate 3D mesh"
fi
