#!/bin/sh 
# make the pdf documentation, the tar packages and set the to dist

modules="models tutorials elmersolver elmergrid cscmodels csctutorials matc overview"
for m in $modules; do
  cd $m && make manual && make install && make clean && cd ..
done

/bin/rm Exclude
find tutorials_files ! -type -print | grep CVS > Exclude
tar cvfX ElmerTutorialsFiles.tar Exclude tutorials_files
/bin/rm Exclude
gzip ElmerTutorialsFiles.tar

find csctutorials_files ! -type -print | grep CVS > Exclude
tar cvfX ElmerTutorialsFilesCSC.tar Exclude csctutorials_files
/bin/rm Exclude
gzip ElmerTutorialsFilesCSC.tar 

mkdir CSCDistro
/bin/mv -f *CSC.pdf *CSC.tar.gz CSCDistro
mkdir Distro
/bin/mv -f *.pdf *.tar.gz Distro
