#!/bin/sh 
# make the pdf documentation, the tar packages and set the to dist

modules="models tutorials elmersolver elmergrid cscmodels csctutorials matc overview elmerparam"
for m in $modules; do
  cd $m && make manual && make install && make clean && cd ..
done

/bin/rm Exclude
find tutorials_files ! -type -print | grep CVS > Exclude
tar cvfX ElmerTutorialsFiles.tar Exclude tutorials_files
/bin/rm Exclude
gzip ElmerTutorialsFiles.tar

find csctutorials_files ! -type -print | grep CVS > Exclude
tar cvfX ElmerTutorialsFilesCSC.tar Exclude csctutorials_files
/bin/rm Exclude
gzip ElmerTutorialsFilesCSC.tar 

# these are not to be distributed
mkdir -p CSCDistro
/bin/mv -f *CSC.pdf *CSC.tar.gz CSCDistro

# this is public stuff
mkdir -p Distro
/bin/mv -f *.pdf *.tar.gz Distro
# use the following kind of command to publish them
# scp Distro/*.* raback@paja.nic.funet.fi:/mnt/nic/data1/content/ftp/pub/sci/physics/elmer/doc