!
! stub header for disabled mpi 
!
       INTEGER MPI_COMM_WORLD
       INTEGER MPI_INTEGER
       INTEGER MPI_STATUS_SIZE
       INTEGER MPI_ANY_SOURCE
       INTEGER MPI_SOURCE
       INTEGER MPI_DOUBLE_COMPLEX
       INTEGER MPI_DOUBLE_PRECISION
