CC	= cc
CFLAGS	= 
OBJ	= nrutil.o common.o femmesh.o femtools.o feminfo.o femfile.o \
	femknot.o fempre.o femelmer.o femfact.o femsolve.o easymesh.o
LIBS	= -L. -lm -lmetis

ElmerGrid: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ) $(LIBS) 

