# Adaptive solver with internal spliting
#

run:
	$(ELMER_HOME)/bin/ElmerGrid 1 2 Ldomain
	$(ELMER_HOME)/bin/Solver

clean:
	/bin/rm test.log temp.log fort.12 mon.out
	/bin/rm -rf Ldomain
	/bin/rm -rf RefinedMesh*
