#!/bin/sh -f

if test "$ELMER_LIB" = ""; then
  if  test "$ELMER_HOME" = ""; then
     INCLUDE=/home/vierinen/src/elmer/buildtools/build.laatikko.2005-07-01-10-16-34/dist/share/elmersolver/include
  else
     INCLUDE=$ELMER_HOME/share/elmersolver/include
  fi
else
  INCLUDE=$ELMER_LIB/../include
fi

cmd="ifc -Vaxlib -O -fPIC -I. -I$INCLUDE  -shared $*"
printf "%s " $cmd
printf "\n"
ifc -Vaxlib -O -fPIC -I. -I$INCLUDE  -shared $*

