#!/bin/sh -f

if test "$ELMER_LIB" = ""; then
  if  test "$ELMER_HOME" = ""; then
     INCLUDE=/Users/vierinen/src/buildtools/build.dhcp-10.csc.fi.2005-06-15-09-44-58/dist/share/elmersolver/include
  else
     INCLUDE=$ELMER_HOME/share/elmersolver/include
  fi
else
  INCLUDE=$ELMER_LIB/../include
fi

cmd="g95 -I$INCLUDE  -dynamiclib -undefined dynamic_lookup -single_module $(LDFLAGS) $*"
printf "%s " $cmd
printf "\n"
g95 -I$INCLUDE  -dynamiclib -undefined dynamic_lookup -single_module $(LDFLAGS) $*

