#!/bin/sh -f

if test "$ELMER_LIB" = ""; then
  if  test "$ELMER_HOME" = ""; then
     INCLUDE=/home/vierinen//share/elmersolver/include
  else
     INCLUDE=$ELMER_HOME/share/elmersolver/include
  fi
else
  INCLUDE=$ELMER_LIB/../include
fi

cmd="g95 -I$INCLUDE  -shared $*"
printf "%s " $cmd
printf "\n"
g95 -I$INCLUDE  -shared $*

