# Transient advection-diffusion test with diffusion through material interface
#
run:
	$(ELMER_HOME)/bin/ElmerGrid 1 2 Step2
	$(ELMER_HOME)/bin/Solver


clean:
	/bin/rm temp.log test.log mon.out
	/bin/rm -r Step2
